name: 'Bump Semantic Version'
description: 'Increment the semver version string in a plain text file.'
inputs:
  file:
    description: 'Plain text file containing a version string.'
    required: true
  version:
    description: 'The version to bump, either major, minor, patch, or infer.'
    required: false
    default: "infer"
  push_options:
    description: 'Options to pass to push, see stefanzweifel/git-auto-commit-action@v4'
    required: false
    default: ""
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: '3.7'
  - run: python ${{ github.action_path }}/bump.py ${{ inputs.file }} ${{ inputs.version }}
    shell: bash
  - uses: stefanzweifel/git-auto-commit-action@v4
    with:
      commit_message: 'docs: auto-update version string'
      file_pattern: '${{ inputs.file }}'
      push_options: '${{ inputs.push_options }}'
